### ISSUE TITLE
Fresh install NoGo  with zip pgk  got info screen this time.

### ISSUE THREAD

**Issue by larrykh465** [atutor/ATutor#158]
with the tar.gz all I got was couldn't access database screen install went thru
with zip i got info screen all went well with the install script
see attached
[infoscreen.txt](https://github.com/atutor/ATutor/files/2259430/infoscreen.txt)

**Comment by gregrgay** [comment]
Unable to reproduce.

**Comment by GaneshKandu** [comment]
Hi,

i am facing same issue on login page after successful install
on login page

because of some reason  ```language_text``` table is not created on installation 

![screenshot-webuzo web-2018-08-06-12-38-11](https://user-images.githubusercontent.com/12833130/43702051-086e7804-9948-11e8-984f-b9eb050aba31.png)

[aTutor224.txt](https://github.com/atutor/ATutor/files/2261480/aTutor224.txt)

**Comment by atutor** [comment]
User support is no longer available for ATutor. If you are able to fix an issue, you can submit a pull request to resolve it.

**Comment by larrykh465** [comment]
I played with it some more. It's not just this version either the legal requirement to provide source code has been met. without "support" a "free download" is all your going to get.   incomplete database import files, the only way, to get working database file to import, you will need to buy support.
